# Generated by Django 5.0.6 on 2024-09-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='historicallisting',
            old_name='title',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='item',
        ),
    ]
