# Generated by Django 5.0.6 on 2024-08-17 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=2048)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('ended', 'Ended')], default='not_started', max_length=20)),
                ('createdTime', models.TimeField(auto_now_add=True)),
                ('updatedTime', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2048)),
                ('comment_time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the what the starting bid should be', max_digits=10)),
                ('bid_time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing')),
            ],
            options={
                'ordering': ['-bid_time'],
            },
        ),
    ]
