# Generated by Django 5.0.6 on 2024-09-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_title_comment_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallisting',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='owner',
        ),
    ]
