# Generated by Django 5.0.6 on 2024-09-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_category_watchlist_unique_tracked_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='comment_time',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
