# Generated by Django 5.0.6 on 2024-08-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_historicallisting_user_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallisting',
            name='url',
            field=models.URLField(blank=True, max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, max_length=200000, null=True),
        ),
    ]
