# Generated by Django 5.0.6 on 2024-09-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comment_comment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imageCategory',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='imageCategory',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
