# Generated by Django 5.0.6 on 2024-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_historicallisting_url_alter_listing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallisting',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
