# Generated by Django 5.0.6 on 2024-09-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_category_imagecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imageCategory',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
